version: "3"
services:
  # SERVER SETUP
  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      AUTH_KEY: ${AUTH_KEY}
      DB_PORT: ${DB_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server:/usr/src/server/
    command: yarn start
  # CLIENT SETUP
  client:
    build: ./client
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/usr/src/client/src
      - ./client/public:/usr/src/client/public
    links:
      - server
    command: serve -p ${REACT_APP_PORT} -s .
